services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\WechatWorkMenuBundle\Controller\:
    resource: '../../Controller/'
  Tourze\WechatWorkMenuBundle\Repository\:
    resource: '../../Repository/'
  Tourze\WechatWorkMenuBundle\Service\:
    resource: '../../Service/'
